import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import 'katex/dist/katex.min.css';
import { parseMessageContent, hasFlashcards, MessageBlock } from '@/utils/flashcardParser';
import FlashcardBlock from './FlashcardBlock';
import FlashcardStudyMode from './FlashcardStudyMode';
import { ParsedFlashcard } from '@/utils/flashcardParser';
import { flashcardService } from '@/services/flashcardService';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from '@/hooks/use-toast';

interface MessageRendererProps {
  content: string;
  role: 'user' | 'assistant';
}

const MessageRenderer: React.FC<MessageRendererProps> = ({ content, role }) => {
  const [studyModeOpen, setStudyModeOpen] = useState(false);
  const [studyFlashcards, setStudyFlashcards] = useState<ParsedFlashcard[]>([]);
  const { user } = useAuth();

  // Preprocess content to convert LaTeX notation
  const preprocessLatex = (text: string): string => {
    // Convert \( ... \) to $ ... $ for inline math (non-greedy match)
    let processed = text.replace(/\\\((.*?)\\\)/g, '$$$1$$');
    // Convert \[ ... \] to $$ ... $$ for display math (non-greedy match)
    processed = processed.replace(/\\\[(.*?)\\\]/gs, '\n$$$$\n$1\n$$$$\n');
    return processed;
  };

  // Parse the message content to separate text and flashcards
  const processedContent = preprocessLatex(content);
  const messageBlocks = parseMessageContent(processedContent);

  const handleStudyMode = (flashcards: ParsedFlashcard[]) => {
    setStudyFlashcards(flashcards);
    setStudyModeOpen(true);
  };

  const handleSaveDeck = async (flashcards: ParsedFlashcard[]) => {
    if (!user) {
      toast({
        title: "Authentication Required",
        description: "Please log in to save flashcard decks.",
        variant: "destructive",
      });
      return;
    }

    try {
      const deckTitle = `AI Generated Deck - ${new Date().toLocaleDateString()}`;
      await flashcardService.saveDeck(user.id, {
        title: deckTitle,
        description: "Generated by AI Assistant",
        flashcards
      });

      toast({
        title: "Deck Saved",
        description: `Saved ${flashcards.length} flashcards to your collection.`,
      });
    } catch (error) {
      toast({
        title: "Save Failed",
        description: "Failed to save flashcard deck. Please try again.",
        variant: "destructive",
      });
    }
  };

  const handleCloseStudyMode = () => {
    setStudyModeOpen(false);
    setStudyFlashcards([]);
  };

  if (role === 'user') {
    return <div className="whitespace-pre-wrap">{content}</div>;
  }

  return (
    <>
      <div className="text-sm leading-relaxed space-y-4">
        {messageBlocks.map((block, index) => {
          if (block.type === 'text') {
            return (
              <ReactMarkdown
                key={`text-${index}`}
                remarkPlugins={[remarkMath]}
                rehypePlugins={[rehypeKatex]}
                components={{
                  // Enhanced styling for better visual hierarchy
                  h1: ({children}) => <h1 className="text-xl font-bold mb-3 text-blue-600 dark:text-blue-400 border-b border-blue-200 dark:border-blue-800 pb-2">{children}</h1>,
                  h2: ({children}) => <h2 className="text-lg font-semibold mb-3 text-gray-700 dark:text-gray-300">{children}</h2>,
                  h3: ({children}) => <h3 className="text-base font-semibold mb-3 text-gray-600 dark:text-gray-400">{children}</h3>,
                  p: ({children}) => <p className="mb-3 text-gray-700 dark:text-gray-300 leading-relaxed">{children}</p>,
                  ul: ({children}) => <ul className="list-disc list-inside mb-4 space-y-2 ml-2 text-gray-700 dark:text-gray-300">{children}</ul>,
                  ol: ({children}) => <ol className="list-decimal list-inside mb-4 space-y-2 ml-2 text-gray-700 dark:text-gray-300">{children}</ol>,
                  li: ({children}) => <li className="text-sm leading-relaxed marker:text-blue-500 dark:marker:text-blue-400">{children}</li>,
                  strong: ({children}) => <strong className="font-bold text-gray-900 dark:text-gray-100 bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20 px-1 py-0.5 rounded">{children}</strong>,
                  em: ({children}) => <em className="italic text-gray-600 dark:text-gray-400">{children}</em>,
                  code: ({children}) => <code className="bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded-md text-xs font-mono text-gray-800 dark:text-gray-200 border border-gray-200 dark:border-gray-700">{children}</code>,
                  blockquote: ({children}) => <blockquote className="border-l-4 border-blue-500 dark:border-blue-400 pl-4 italic text-gray-600 dark:text-gray-400 bg-blue-50 dark:bg-blue-900/10 py-2 rounded-r-lg">{children}</blockquote>,
                  a: ({children, href}) => <a href={href} className="text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 underline decoration-blue-300 dark:decoration-blue-600 hover:decoration-blue-500 transition-colors">{children}</a>,
                }}
              >
                {block.content}
              </ReactMarkdown>
            );
          } else if (block.type === 'flashcards') {
            return (
              <FlashcardBlock
                key={`flashcards-${index}`}
                flashcards={block.flashcards}
                totalCount={block.totalCount}
                onStudyMode={handleStudyMode}
                onSaveDeck={handleSaveDeck}
              />
            );
          }
          return null;
        })}
      </div>

      {/* Study Mode Modal */}
      {studyModeOpen && (
        <FlashcardStudyMode
          flashcards={studyFlashcards}
          onClose={handleCloseStudyMode}
          onSave={handleSaveDeck}
        />
      )}
    </>
  );
};

export default MessageRenderer;
