// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Default to production URLs unless env vars are provided
const SUPABASE_URL = "https://eakktmgnlwatvrgmjcok.supabase.co";
  // import.meta.env.VITE_SUPABASE_URL ||
  // "https://eakktmgnlwatvrgmjcok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVha2t0bWdubHdhdHZyZ21qY29rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNDM4MTQsImV4cCI6MjA1NzkxOTgxNH0.T4iG0f02Ar5IWIRHXbHh8HCpNEvDfwOFHE0EX_bzIxc";
  // import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  // "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVha2t0bWdubHdhdHZyZ21qY29rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNDM4MTQsImV4cCI6MjA1NzkxOTgxNH0.T4iG0f02Ar5IWIRHXbHh8HCpNEvDfwOFHE0EX_bzIxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

console.log("Creating Supabase client with URL:", SUPABASE_URL);
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
